apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: vbnpr0mov-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/vbnpr0mov-java-springboot-gitops